# Configuration for KartaAutoAnnouncer
# The interval in seconds between each announcement.
interval: 60

# Prefix settings for CHAT announcements.
prefix:
  # Set to true to enable the prefix, false to disable it.
  enabled: true
  # The text to be displayed as the prefix.
  text: "&d[Karta] &r"

# A list of messages to be broadcast.
# You can enable or disable each announcement type individually.
# Color codes (&a, &b, etc.) and hex colors (&#RRGGBB) are supported in all text fields.
announcements:
  chat:
    # Set to true to enable chat announcements, false to disable.
    enabled: true
    messages:
      - "This is a single-line chat message."
      - [
          "This is a multi-line message.",
          "This is the second line."
        ]
  action_bar:
    # Set to true to enable action bar announcements, false to disable.
    enabled: true
    messages:
      - "&aThis is an action bar message."
      - "&eCheck out our website!"
  title:
    # Set to true to enable title announcements, false to disable.
    enabled: true
    messages:
      - title: "&6Welcome!"
        subtitle: "&fEnjoy your stay on our server."
      - title: "&cVote for us!"
        subtitle: "&fReceive rewards for your support."