name: KartaAutoAnnouncer
version: 1.3.0
main: com.minekarta.autoannouncer.AutoAnnouncer
api-version: 1.21
description: A simple plugin to automatically broadcast messages.
depend: [PlaceholderAPI]
commands:
  kartaautoannouncer:
    description: Main command for the AutoAnnouncer plugin.
    usage: /<command> [reload|add|setinterval]
    aliases: [kaa]
permissions:
  autoannouncer.admin:
    description: Allows access to all admin commands for AutoAnnouncer.
    default: op
